name: credit_card_displayer
description: "A very easy-to-use package to display credit card with the appropriate logo, according to the credit card first number"
version: 0.0.6
homepage: https://github.com/Hery34/credit_card_displayer.git

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  assets:
    - lib/assets/visa.png
    - lib/assets/mastercard.png
    - lib/assets/amex.png