name: credit_card_displayer
description: "A very easy-to-use package to display credit card logos, according to the card number."
version: 0.0.3
homepage: https://github.com/Hery34/credit_card_displayer.git

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/